name: shmetro 
  
on:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * *' 

jobs:  
   build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - uses: actions/checkout@v2  
  
    # 安装Python  
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12" 
  
    # 安装依赖  
    - name: Install dependencies  
      shell: bash  
      run: |  
        echo "Installing dependencies..."  
        python -m pip install --upgrade pip  
        pip install bs4 Path argparse requests
  
    # 运行Python脚本  
    - name: Run Python script  
      shell: bash  
      run: |  
        python sitecopy.py -u "https://shmetro.fandom.com/zh/wiki/%E4%B8%8A%E6%B5%B7%E5%9F%8E%E5%B8%82%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A_Wiki" -e -d 1000 -t 50  
  
    # 打包文件  
    - name: Zip files  
      shell: bash  
      run: |  
        zip -r website.zip website
  
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: website.zip
          path: website.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          website.zip
        tag_name: shmetro.fandom.com/zh      
